In [1]:
import torch
print(torch.__version__)  # 설치된 PyTorch 버전 출력
print(torch.cuda.is_available())  # CUDA 사용 가능 여부 확인

if torch.cuda.is_available():
    print(f"GPU 사용 가능: {torch.cuda.get_device_name(0)}")
else:
    print("GPU를 사용할 수 없습니다. CPU를 사용합니다.")

x = torch.rand(3, 3)
y = torch.rand(3, 3)
z = x + y
print("x:", x)
print("y:", y)
print("z:", z)

2.8.0+cpu
False
GPU를 사용할 수 없습니다. CPU를 사용합니다.
x: tensor([[0.8983, 0.5563, 0.8469],
        [0.9290, 0.5762, 0.0195],
        [0.5579, 0.9740, 0.6992]])
y: tensor([[0.9512, 0.2876, 0.4320],
        [0.5015, 0.2227, 0.0148],
        [0.7606, 0.1543, 0.9811]])
z: tensor([[1.8495, 0.8438, 1.2790],
        [1.4305, 0.7989, 0.0343],
        [1.3186, 1.1283, 1.6803]])


In [7]:
x = torch.ones(3, 3)  # 기존 텐서
print(x)
rand_tensor = torch.randint_like(x, 0, 10)  # 기존 크기 유지, 0~9 정수 샘플링

print(rand_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 8., 4.],
        [2., 7., 9.],
        [9., 8., 5.]])


In [8]:
mean = torch.tensor([0.0, 2.0, 4.0])  # 평균
std = torch.tensor([1.0, 0.5, 0.1])  # 표준편차

tensor = torch.normal(mean, std)  # 각 요소별로 지정한 평균과 표준편차 적용

print(tensor)

tensor([0.0166, 1.7078, 3.8933])


In [9]:
tensor = torch.randperm(10)  # 0~9 정수를 무작위 섞기
print(tensor)


tensor([5, 0, 2, 1, 3, 6, 9, 7, 8, 4])


In [20]:
probs = torch.tensor([0.2, 0.8, 0.5, 0.9])  # 0~1 사이 확률값

tensor = torch.bernoulli(probs)  # 각 확률에 따라 0 또는 1 생성

print(tensor)

tensor([0., 1., 0., 1.])


In [26]:
probs = torch.tensor([0.1, 0.2, 0.3, 0.4])  # 각 요소의 선택 확률
tensor = torch.multinomial(probs, 2, replacement=True)  # 2개 선택 (복원 추출)
print(tensor)

tensor([3, 3])


In [32]:
torch.manual_seed(41)  # 시드 고정
print(torch.rand(3, 3))  # 동일한 난수 생성

tensor([[0.2364, 0.2266, 0.8005],
        [0.1692, 0.2650, 0.7720],
        [0.1282, 0.7452, 0.8045]])


In [33]:
import torch

# 기존 텐서
x = torch.tensor([1, 2, 3], dtype=torch.float32)

# 일반 연산 (새로운 텐서 반환)
y = x + 10
print("x (원본):", x)  # 원본 텐서 변경 없음
print("y (새로운 텐서):", y)  # 새로운 텐서 생성됨

# 인플레이스 연산
x.add_(10)
print("x (인플레이스 연산 후):", x)  # 기존 텐서가 변경됨

x (원본): tensor([1., 2., 3.])
y (새로운 텐서): tensor([11., 12., 13.])
x (인플레이스 연산 후): tensor([11., 12., 13.])


In [34]:
import torch

x = torch.arange(6)  # 1D 텐서 (0~5)
print("Original Shape:", x.shape)

xreshaped = x.view(2, 3)  # 2행 3열로 변경

print("Reshaped Shape:", xreshaped.shape)
print(xreshaped)

Original Shape: torch.Size([6])
Reshaped Shape: torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [35]:
x = torch.arange(24).view(2, 3, 4)  # 3D 텐서 생성 (배치=2, 행=3, 열=4)

print("3D Tensor Shape:", x.shape)

xflattened = x.view(2, -1)  # 배치 유지, 나머지는 자동 조정
print("Flattened Shape:", xflattened.shape)

3D Tensor Shape: torch.Size([2, 3, 4])
Flattened Shape: torch.Size([2, 12])


In [36]:
import torch

x = torch.randn(1, 3, 1, 4)  # (Batch=1, Channels=3, Height=1, Width=4)

x_squeezed = x.squeeze()  # 크기가 1인 차원을 제거

print(x.shape)          # torch.Size([1, 3, 1, 4])
print(x_squeezed.shape) # torch.Size([3, 4])

torch.Size([1, 3, 1, 4])
torch.Size([3, 4])


In [38]:
y = torch.randn(3, 4)  # (3, 4) 형태
y_unsqueezed = y.unsqueeze(2)  # 0번 차원 추가

print(y.shape)           # torch.Size([3, 4])
print(y_unsqueezed.shape) # torch.Size([1, 3, 4])

torch.Size([3, 4])
torch.Size([3, 4, 1])
